"""add research retry metadata

Revision ID: 4e3740a9e114
Revises: b983672d1607
Create Date: 2026-08-23 20:46:32.336815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3740a9e114'
down_revision: Union[str, Sequence[str], None] = 'b983672d1607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_research', sa.Column('attempt', sa.Integer(), server_default='0', nullable=False))
    op.add_column('company_research', sa.Column('last_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_research', 'last_error')
    op.drop_column('company_research', 'attempt')
    # ### end Alembic commands ###
