"""add outbox claimed at

Revision ID: 9a78b73ce72a
Revises: 1051ac5633d7
Create Date: 2026-08-29 14:25:28.554661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a78b73ce72a'
down_revision: Union[str, Sequence[str], None] = '1051ac5633d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_events', 'claimed_at')
    # ### end Alembic commands ###
