"""add extracted text to company research

Revision ID: b983672d1607
Revises: 4571956fda04
Create Date: 2026-08-21 23:48:32.959998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b983672d1607'
down_revision: Union[str, Sequence[str], None] = '4571956fda04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_research', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_research', 'extracted_text')
    # ### end Alembic commands ###
