services:


  redis:
    image: redis/redis-stack-server:latest
    container_name: outreach_redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    environment:
      REDIS_ARGS: "--appendonly yes"

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      

  rabbitmq:
    image: rabbitmq:3-management
    container_name: outreach_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: outreach
      RABBITMQ_DEFAULT_PASS: outreach_password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  qdrant:
    image: qdrant/qdrant
    container_name: outreach_qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  redis_data:
  rabbitmq_data:
  qdrant_data: